version: "3.9"

services:
  app:
    build: .
    container_name: syria-gpt-app
    command: uvicorn main:app --host 0.0.0.0 --port 9000 --reload
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    depends_on:
      - db
      - qdrant

  db:
    image: postgres:15
    container_name: syria-gpt-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: syriagpt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:v1.7.0
    container_name: syria-gpt-qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

  pgadmin:
    image: dpage/pgadmin4
    container_name: syria-gpt-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
  qdrant_data:
