"""Add 2FA secret to user model

Revision ID: 08f8ed452566
Revises: 001
Create Date: 2025-08-24 17:32:29.212313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '08f8ed452566'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('two_factor_secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'two_factor_secret')
    # ### end Alembic commands ###