"""add_questions_and_answers_tables

Revision ID: 9c30c212603e
Revises: 2317d17ec818
Create Date: 2025-08-29 12:53:21.548334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9c30c212603e'
down_revision: Union[str, None] = '2317d17ec818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###